version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789qwe123!
      POSTGRES_DB: bd_for_junior_blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:123456789qwe123!@db:5432/bd_for_junior_blog
    depends_on:
      - db

volumes:
  postgres_data: